[package]
name = "rustvault"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
rand = "0.9.0"
rusqlite = { version = "0.34.0", features = ["bundled"] }
